services:
  web:
    container_name: web-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    container_name: db-dev
    image: mariadb:lts
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=gestionale_pcto
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravel
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin-dev
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80

volumes:
  db_data:
